// Angular/src/app/components/managers/product/create-product/create-product.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductService, AuthService, OnInitService } from '../../../../servises';
import { Router } from '@angular/router';

@Component({
  selector: 'app-create-product',
  templateUrl: './create-product.component.html',
  styleUrls: ['./create-product.component.css']
})
export class CreateProductComponent implements OnInit {

  constructor(private productService: ProductService,
              private router: Router,
              private onInitService: OnInitService) { }

  form = {
    name:'',
    category: '',
    price: 0,
    exist: true
  }
  ngOnInit() {
    this.onInitService.checkPermission('CreateProduct');
  }
  onSubmit(){
    this.productService.saveProduct(this.form)
    this.router.navigateByUrl('/');
  }
}


<form class="form-group">
    <label for="nameInput">Name</label>
    <input type="text" 
           id="nameInput" 
           class="form-control" 
           [(ngModel)]="form['name']"
           [ngModelOptions]="{standalone: true}">
    <label for="nameInput">Category</label>
    <input type="text" 
           id="nameInput" 
           class="form-control" 
           [(ngModel)]="form['category']"
           [ngModelOptions]="{standalone: true}">
    <label for="nameInput">Price</label>
    <input type="number" 
           id="nameInput" 
           class="form-control" 
           [(ngModel)]="form['price']"
           [ngModelOptions]="{standalone: true}">
    <label for="existBox">Exist in store</label>
    <input [checked]="form['exist']"
           (change)="form.exist = !form.exist"
           type="checkBox" 
           id="existBox" 
           class="form-check">
    <button type="button" 
            (click)="onSubmit()" 
            class="btn btn-success">Submit</button>
</form>

// Vue/src/components/CreateProduct.vue
<template>
    <div>
        <form class="form-group" @submit.prevent="onSubmit">
            <label for="nameInput">Name</label>
            <input type="text" id="nameInput" class="form-control" v-model="form['name']">
            <label for="nameInput">Category</label>
            <input type="text" id="nameInput" class="form-control" v-model="form['category']">
            <label for="nameInput">Price</label>
            <input type="number" id="nameInput" class="form-control" v-model="form['price']">
            <label for="existBox">Exist in store</label>
            <input type="checkBox" id="existBox" class="form-check"
                   :checked="form['exist']" @change="onChange">
            <button class="btn btn-success">Submit</button>
        </form>
    </div>
</template>

<script>
import {mapActions} from 'vuex';

export default {
    data(){
        return{
            form:{
                name: '',
                category: '',
                price: 0,
                exist: true,
                framework: 'Vue'
            },
        }
    },
    methods:{
        ...mapActions({
            saveProduct : 'products/saveProduct',
            updateData : 'products/updateData',
        }),
        onSubmit(e){
            this.saveProduct(this.form)
            .then(()=>{
                this.updateData()
            })
            .then(()=>{
                this.$router.push('/products');
            })
        },
        onChange(e){
            this.form['exist'] = e.target.checked;
        }
    }
}
</script>

<style scoped>
.btn{
    display: block;
    margin: 5px auto;
}
</style>
