// Vue/src/components/Auth/Register.vue
<template>
    <div>
        <h2 class="text-center">Registration new account</h2>
        <form calss="form-group" @submit.prevent="onSubmit()">
            <label for="loginInput">Login</label>
            <input type="text" id="loginInput" class="form-control" v-model="form['login']">
            <label for="passwordInput">Password</label>
            <input type="password" id="passwordInput" class="form-control" v-model="form['password']">
            <button class="btn btn-success">Submit</button>
        </form>
    </div>
</template>


<script>
import {mapActions} from 'vuex';

export default {
    data() {
        return{
            form: {
                login: '',
                password: ''
            }
        }
    },
    methods:{
        ...mapActions({
            register: 'auth/register'
        }),
        onSubmit(){
            this.register(this.form);
            this.$router.push('/login');
        }
    }
}
</script>

<style scoped>
.btn{
    display: block;
    margin: 10px auto;
}
</style>

// Angular/src/app/components/auth/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../../servises';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {

  constructor(private authService: AuthService,
              private router: Router) { }

  form = {
    login: '',
    password: ''
  }

  ngOnInit() {
    if (this.authService.isAuthenticated){
      this.router.navigateByUrl('/');
    }
  }

  onSubmit(){
    this.authService.register(this.form)
    this.router.navigateByUrl('/login');
  }
}

<h2 class="text-center">Registration new account</h2>
<form calss="form-group">
    <label>Login</label>
    <input type="text" 
           class="form-control" 
           [(ngModel)]="form.login" 
           [ngModelOptions]="{standalone: true}" >
    <label>Password</label>
    <input type="password" 
           class="form-control" 
           [(ngModel)]="form.password" 
           [ngModelOptions]="{standalone: true}">
    <button type="button"
            (click)="onSubmit()" 
            class="btn btn-success">Submit</button>
</form>
