// Angular/src/app/components/managers/menu-roles/menu-roles.component.ts
import { Component, OnInit } from '@angular/core';
import { RoleMenuService, AuthService, OnInitService } from '../../../servises';
import { Permission, RoleJson } from '../../../models';
import { Router } from '@angular/router';

@Component({
  selector: 'app-menu-roles',
  templateUrl: './menu-roles.component.html',
  styleUrls: ['./menu-roles.component.css'],
  providers: [RoleMenuService]
})
export class MenuRolesComponent implements OnInit {

  constructor(private roleMenuService: RoleMenuService,
              private onInitService: OnInitService) { }

  private checkedRole: RoleJson;
  private permissionCheckBoxList: string[] =  [];
  private addRole: boolean = true;
  private newRoleName: string = '';
  get permissions(): Permission[]{
    return this.roleMenuService.getAllPermissions();
  }
  get roles(): RoleJson[]{
    return this.roleMenuService.getAllRoles();
  }
  get view(): boolean{
    return this.roles.length > 0 && this.permissions.length > 0;
  }
  
  ngOnInit() {
    this.onInitService.checkPermission('AccessToRoleManager',()=>{
      return this.roleMenuService.updateData();
    })
  }
  onClick(role){
    this.checkedRole = role;
    this.permissionCheckBoxList = [];
    this.addRole = false;
    for(let p of role.permissions){
      this.permissionCheckBoxList = this.permissionCheckBoxList.concat(p);
    }
  }
  submit(){
    this.roleMenuService.updateRole({
      roleId: this.checkedRole.roleId,
      name: this.checkedRole.name,
      permissions: this.permissionCheckBoxList
    })
    this.back();
  }
  addNewRole(){
    this.roleMenuService.saveRole(this.newRoleName)
    this.newRoleName = '';
  }
  deleteRole(){
    this.roleMenuService.removeRole(this.checkedRole.name)
    this.back();
  }
  back(){
    this.checkedRole = null,
    this.permissionCheckBoxList = [];
    this.addRole = true;
  }
  getClass(roleId){
    if (this.checkedRole){
      return this.checkedRole.roleId == roleId ? 'checked' : '';
    }
  }
  onChangeCheckbox(permission){
    if (this.permissionCheckBoxList.indexOf(permission.name) > -1){
      this.permissionCheckBoxList = this.permissionCheckBoxList.filter(el=>el!=permission.name);
    }else{
      this.permissionCheckBoxList = this.permissionCheckBoxList.concat(permission.name);
    }
  }
}

<div *ngIf="view">
  <div class="d-flex flex-nowrap bd-highlight">
    <div *ngFor="let role of roles"
        (click)="onClick(role)"
        [class]="getClass(role.roleId) + ' p-2 bd-highlight border role'">
        {{role.name}}
    </div>
  </div>
  <div *ngIf="!addRole">
    <div>
      <div *ngFor="let permission of permissions">
      <input type="checkbox" 
              [id]="permission.name" 
              [value]="permission.name"
              [checked]="permissionCheckBoxList.indexOf(permission.name) > -1"
              (change)="onChangeCheckbox(permission)">
      <label>{{permission.name}}</label>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <button class="btn" (click)="back()">Back</button>
      <button class="btn btn-success" (click)="submit()">Submit</button>
      <button class="btn" (click)="deleteRole()">Delete Role</button>
    </div>
  </div>
  <div *ngIf="addRole">
    <hr>
    <input type="text" 
          [(ngModel)]="newRoleName" 
          placeholder="Write new role name"
          class="form-control">
    <button class="btn d-block mx-auto" 
            (click)="addNewRole()">Add role</button>
  </div>
<div>

// Vue/src/components/Menu/MenuRoles.vue
<template>
    <div>
        <div class="d-flex flex-nowrap bd-highlight">
            <div v-for="role in roles"
                :key="role.roleId"
                @click="onClick(role)"
                :class="getClass(role.roleId)"
                class="p-2 bd-highlight border">
                {{role.name}}
            </div>
        </div>
        <template v-if="!addRole">
        <div>
            <div v-for="permission in permissions"
                    :key="permission.permissionId">
            <input type="checkbox" 
                    :id="permission.name" 
                    :value="permission.name"
                    v-model="permissionCkeckBoxList">
            <label>{{permission.name}}</label>
            </div>
        </div>
        <div class="d-flex justify-content-center">
            <button class="btn" @click="back">Back</button>
            <button class="btn btn-success" @click="submit">Submit</button>
            <button class="btn" @click="deleteRole">Delete Role</button>
        </div>
        </template>
        <template v-if="addRole">
        <hr>
        <input type="text" 
                v-model="newRoleName" 
                placeholder="Write new role name"
                class="form-control">
        <button class="btn d-block mx-auto" 
                @click="addNewRole">Add role</button>
        </template>
    </div>
</template>

<script>
import {mapActions,mapGetters} from 'vuex';
export default {
    data(){
        return {
            checkedRole: {},
            permissionCkeckBoxList: [],
            addRole: true,
            newRoleName: '',
        }
    },
    methods : {
        ...mapActions({
            updateData : 'roleManager/updateData',    
            updateRole : 'roleManager/updateRole',
            removeRole : 'roleManager/removeRole',
            saveRole : 'roleManager/saveRole',

        }),
        onClick(role){
            this.checkedRole = role;
            this.permissionCkeckBoxList = [];
            this.addRole = false;
            for(let p of role.permissions){
                this.permissionCkeckBoxList.push(p);
            }
        },
        submit(){
            this.updateRole({
                roleId: this.checkedRole.roleId,
                name: this.checkedRole.name, 
                permissions: this.permissionCkeckBoxList
            })
            .then(()=>{
                this.back();
            })
        },
        addNewRole(){
            this.saveRole(this.newRoleName)
            .then(()=>{
                this.newRoleName = '';
                this.updateData();
            })
        },
        deleteRole(){
            this.removeRole(this.checkedRole.name)
            .then(()=>{
                this.updateData();
                this.back();
            })
        },
        back(){
            this.checkedRole = '',
            this.permissionCkeckBoxList = [];
            this.addRole = true;
        },
        getClass(roleId){
            return this.checkedRole.roleId === roleId ? ' checked' : '';
        }
    },
    computed:{
        ...mapGetters({
           permissions : 'roleManager/allPermissions',
           roles : 'roleManager/allRoles'
        }),
        checkboxValue(permission){
            return 
        }
    }
}
</script>

<style scoped>
.btn{
    margin: 10px 5px;
}
.border{
    padding: 10px;
    margin: 5px;
    transition: background 0.3s, color 0.3s;
}
.checked{
    background-color: #0278ff;
    color: white;
}
</style>
