// React/src/components/auth/login/login.component.js
import React, { Component } from 'react';
import {connect} from 'react-redux'

import './login.component.css';
import {
    loginRequest,
    getIsLogined,
    getIsLoginLoading,
    getIsLogout,
    getError
} from '../../../ducks/auth';


const mapStateToProps = state =>({
    isLogined: getIsLogined(state),
    isLogout: getIsLogout(state),
    isLoginLoading: getIsLoginLoading(state),
    error: getError(state)
})

const mapDispathToProps = {
    loginRequest
}

class LoginComponent  extends Component{
    static getDerivedStateFromProps(nextProps,nextState){
        if(nextProps.isLogined || nextProps.isLoginLoading) {
            nextProps.history.push('/');
        }
        return nextState;
    }
    state = {
        form: {
            login: '',
            password: ''
        }
    }
    handleChange = (event) => {
        const {name,value} = event.target;
        this.setState(state=>({
            ...state,
            form:{
                ...state.form,
                [name]:value
            }
        }))
    }
    submit=()=>{
        let {loginRequest, history} = this.props;
        let {form} = this.state;
        loginRequest(form);
        history.push('/');
    }
    render(){
        let {history} = this.props;
        let {login,password} = this.state.form;
        return (
            <div>
                <h2 className="text-center">Login in your account</h2>
                <div className="form-group">
                    <label>Login</label>
                    <input 
                        name="login"
                        value={login}
                        onChange={this.handleChange}
                        type="text" 
                        className="form-control"
                        />
                    <label>Password</label>
                    <input 
                        name="password"
                        value={password}
                        onChange={this.handleChange}
                        type="password" 
                        className="form-control"/>
                    <button 
                        onClick={this.submit}
                        className="btn btn-success btn-center">
                    Submit</button>
                </div>
                <button type="button" 
                        onClick={()=>{history.push('/registration')}}
                        className="btn btn-center">
                    Or create new Account
                </button>
            </div>
        )
    }
}

export default connect(
    mapStateToProps,
    mapDispathToProps
)(LoginComponent);

// Vue/src/components/Auth/Login.vue
<template>
    <div>
        <h2 class="text-center">Login in your account</h2>
        <form calss="form-group" @submit.prevent="onSubmit()">
            <label for="loginInput">Login</label>
            <input type="text" id="loginInput" class="form-control" v-model="form['login']">
            <label for="passwordInput">Password</label>
            <input type="password" id="passwordInput" class="form-control" v-model="form['password']">
            <button class="btn btn-success">Submit</button>
        </form>
        <button type="button" 
                @click="register()"
                class="btn">
            Or create new Account</button>
    </div>
</template>


<script>
import {mapActions} from 'vuex';

export default {
    data() {
        return{
            form: {
                login: '',
                password: ''
            }
        }
    },
    methods:{
        ...mapActions({
           login: 'auth/login' 
        }),
        onSubmit(){
            this.login(this.form)
            .then(()=>{
                this.$router.push('/products');
            })
        },
        register(){
            this.$router.push('/registration');
        }
    }
}
</script>

<style scoped>
.btn{
    display: block;
    margin: 10px auto;
}
</style>
