// Angular/src/app/components/auth/login/login.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import {AuthService} from '../../../servises';
import {Router} from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor(private authService: AuthService,
              private router: Router,
              private cd: ChangeDetectorRef) { }
  form = {
    login: '',
    password: ''
  }
  ngOnInit() {
    if(this.authService.isAuthenticated){
      this.router.navigateByUrl('/');
    }
  }
  onSubmit(){
    this.authService.login(this.form)
    this.router.navigateByUrl('/');
  }
  register(){
    this.router.navigateByUrl('/register');
  }
}

<div>
    <h2 class="text-center">Login in your account</h2>
    <form calss="form-group">
        <label>Login</label>
        <input type="text" 
               class="form-control" 
               [(ngModel)]="form['login']" 
               [ngModelOptions]="{standalone: true}" >
        <label>Password</label>
        <input type="password" 
               class="form-control" 
               [(ngModel)]="form['password']"
               [ngModelOptions]="{standalone: true}">
        <button (click)="onSubmit()"
                type="button" 
                class="btn btn-success">Submit</button>
    </form>
    <button type="button" 
            (click)="register()"
            class="btn">
        Or create new Account</button>
</div>

// Vue/src/components/Auth/Login.vue
<template>
    <div>
        <h2 class="text-center">Login in your account</h2>
        <form calss="form-group" @submit.prevent="onSubmit()">
            <label for="loginInput">Login</label>
            <input type="text" id="loginInput" class="form-control" v-model="form['login']">
            <label for="passwordInput">Password</label>
            <input type="password" id="passwordInput" class="form-control" v-model="form['password']">
            <button class="btn btn-success">Submit</button>
        </form>
        <button type="button" 
                @click="register()"
                class="btn">
            Or create new Account</button>
    </div>
</template>


<script>
import {mapActions} from 'vuex';

export default {
    data() {
        return{
            form: {
                login: '',
                password: ''
            }
        }
    },
    methods:{
        ...mapActions({
           login: 'auth/login' 
        }),
        onSubmit(){
            this.login(this.form)
            .then(()=>{
                this.$router.push('/products');
            })
        },
        register(){
            this.$router.push('/registration');
        }
    }
}
</script>

<style scoped>
.btn{
    display: block;
    margin: 10px auto;
}
</style>
