// React/src/containers/App.js
import React, { Component } from 'react';
import { NavLink, withRouter } from 'react-router-dom';
import {connect} from 'react-redux'

import './App.css';
import router from  './router';

import {
  loadPermissionsRequest,
  getPermissions,
  getIsLogined,
  getIsLogout,
  getIsLoginLoading,
  logout
 } from '../ducks/auth';

const mapStateToProps = state =>({
  permissions: getPermissions(state),
  isLogined: getIsLogined(state),
  isLogout: getIsLogout(state),
  IsLoginLoading: getIsLoginLoading(state)
})

const mapDispathToProps = {
  logout,
  loadPermissionsRequest
}

class App extends Component {
  constructor(props){
    if(props.isLogined){
      props.loadPermissionsRequest();
    }
    super(props);
  }
  render() {
    let {
      permissions,
      isLogined,
      isLogout,
      IsLoginLoading,
      logout} = this.props;
    return (
      <div className="App">
       <header>
          <h1>Welcome</h1>
        </header>
        <main>
          <nav>
            <ul>
              {
                ( isLogined && permissions.includes("CreateProduct")) 
                && <li className="list-group-item">
                    <NavLink to="/create-product">Create Product</NavLink>
                  </li>
              }
              <li className="list-group-item">
                <NavLink to="/">Table</NavLink>
              </li>
              {
                isLogout 
                && <li className="list-group-item">
                    <NavLink to="/login">Login</NavLink>
                   </li>
              }
              {
                IsLoginLoading
                && <li className="list-group-item">
                      <span>Загрузка</span>
                   </li>
              }
              {
                isLogined
                && <li className="list-group-item">
                      <span onClick={()=>{logout()}}>Logout</span>
                   </li>
              }
              {
                ( isLogined && permissions.includes("ShowAccessUsers")) 
                && <li className="list-group-item">
                    <NavLink to="/access-users">Access Users</NavLink>
                  </li>
              }
              {
                ( isLogined && permissions.includes("AccessToRoleManager")) 
                && <li className="list-group-item">
                    <NavLink to="/role-manager">Role Manger</NavLink>
                  </li>
              }
              {
                ( isLogined && permissions.includes("AccessToUserManager")) 
                && <li className="list-group-item">
                    <NavLink to="/user-manager">User Manger</NavLink>
                  </li>
              }
            </ul>
          </nav>
          <div className="content">
            {router()}
          </div>
        </main>
      </div>
    );
  }
}

export default withRouter(connect(
  mapStateToProps,
  mapDispathToProps
)(App));

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import {AuthService, OnInitService} from './servises';
import { Router } from '@angular/router';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  constructor(private authService: AuthService,
              private onInitService: OnInitService,
              public router: Router) {}
  
  showNav = false;

  get showLoadingIndicator() : boolean{
    return this.onInitService.status;
  }
  get isAuth():boolean{
    return this.authService.isAuthenticated;
  }
  get permissions(): string[]{
    return this.authService.getPermissions();
  }
  get createProduct(): boolean{
    return this.authService.checkPermission('CreateProduct');
  }
  get accessUsers(): boolean{
    return this.authService.checkPermission('ShowAccessUsers');
  }
  get roleMenu(): boolean{
    return this.authService.checkPermission('AccessToRoleManager');
  }
  get userMenu(): boolean{
    return this.authService.checkPermission('AccessToUserManager');
  }
  get mounted(): boolean{
    return true;
  }
  ngOnInit(){
    if (this.isAuth){
      this.authService.updatePermissionsList().subscribe(()=>{
        this.showNav = true;
      })
    }else{
      this.showNav = true;
    }
  }
  logout(){
    this.authService.logout();
    this.router.navigateByUrl('/');
  }
}

<div>
    <header>
        <h1>Welcome</h1>
    </header>
    <main>
        <nav [class]="showNav ? '' : 'hidden'">
            <ul class="list-group">
                <li (click)="router.navigateByUrl('/createProduct')"
                    class="list-group-item" 
                    *ngIf="createProduct">
                    Create Product
                </li>
                <li class="list-group-item"
                    (click)="router.navigateByUrl('/')">
                    Products
                </li>
                <li class="list-group-item" 
                    (click)="router.navigateByUrl('/login')"
                    *ngIf="!isAuth">
                    Login
                </li>
                <li class="list-group-item" 
                    (click)="logout()"
                    *ngIf="isAuth">
                    Logout
                </li>
                <li (click)="router.navigateByUrl('/accessUsers')"
                    class="list-group-item" 
                    *ngIf="accessUsers">
                    Access Users
                </li>
                <li (click)="router.navigateByUrl('/roleMenu')"
                    class="list-group-item" 
                    *ngIf="roleMenu">
                    Role Menu
                </li>
                <li (click)="router.navigateByUrl('/userMenu')"
                    class="list-group-item" 
                    *ngIf="userMenu">
                    User Menu
                </li>
            </ul>
        </nav>
        <div class="content">
            <div class="d-flex justify-content-center align-items-center">
            <div [class]="showLoadingIndicator ? '' : 'hidden'"><div class="loader"></div></div>
            </div>
            <div [class]="showLoadingIndicator ? 'hidden' : ''">
                <router-outlet></router-outlet>
            </div>
        </div>
    </main>
</div>
