// React/src/components/table/table.component.js
import React, { Component } from 'react';
import TBody from './tbody.component';
import THead from './thead.combonent';
import './table.component.css';

export default class AppTable extends Component{
    static getDerivedStateFromProps(nextProps,nextState){
        let {data,remove} = nextProps;
        if(data.length > 0){
            let filter = {};
            let removedElement = Object.keys(data[0])
                                    .filter(key=>{
                                        return !(remove && remove.map(el=>el.toUpperCase()).includes(key.toUpperCase()))
                                    })
            for(let key of removedElement){
                filter[key] = (typeof(data[0][key]) == "boolean") ? false : '';
            }
            
            if(nextState && nextState.filter){
                for(let key in filter){
                    if(nextState.filter[key]){
                        filter[key] = nextState.filter[key];
                    }
                }
            }

            return {
                ...nextState,
                filter
            }
        }else{
            return{
                ...nextState
            }
        }
    }
    filterItems(name,value){
        let filter = {
            ...this.state.filter,
            [name]:value
        }
        this.setState((state)=>({
            ...state,
            filter
        })) 
    }
    handleInput = (event) => {
        const {name,type,value,checked} = event.target
        let currentValue;
        switch (type){
            case "text" :
            currentValue = value;
                break;
            case "checkbox":
            currentValue = checked;
                break;
            default:
                throw new Error("unsupported type");
        }
        this.setState((state)=>({
            ...state,
            filter: {
                ...state.filter,
                [name]:currentValue
            }
        }))
    }
    get filterData(){
        let {data} = this.props;
        let {filter} = this.state;

        return data.filter((item) => {
            for(let key in filter){
                let check = typeof(data[0][key]) == "boolean"
                        ? ((filter[key] && item[key]) || !filter[key])
                        : (item[key].toString().toUpperCase().indexOf(filter[key].toString().toUpperCase()) !== -1);
                if (!check) return false;
            }
            return true;
        })
    }
    render(){
        let {data,remove,button,buttonClick}  = this.props;
        let {filter} = this.state;
        return (
            <div>
                {this.filter}
                <table className="table table-bordered">
                    <THead
                        data={data.length > 0 ? data[0] : null}
                        filter={filter}
                        remove={remove}
                        button={button}
                        handleInput={this.handleInput.bind(this)}
                        />
                    <TBody 
                        data={this.filterData}
                        button={button}
                        buttonClick={buttonClick}
                        remove={remove}/>
                </table>
            </div>
        );
    }
}

// Angular/src/app/components/table/table.component.ts
import { Component, OnInit, Input, Output, EventEmitter} from '@angular/core';
import { CurrentDataPipe } from '../../pipes';

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css']
})
export class TableComponent implements OnInit {

  @Input() data : string[];
  @Input() button : string; 
  @Input() remove : string[];

  @Output() buttonClick = new EventEmitter<object>();

  filter = {};
  constructor() { }
  get viewTable(){
    return this.data.length > 0;
  }
  ngOnInit() {
    let currentData = new CurrentDataPipe().transform(this.data,this.remove);
    for(let key in currentData[0] ){
        this.filter[key] = (typeof(this.data[0][key]) == "boolean") ? false : '';
    }
  }
  jsUcfirst(string){
    return string.charAt(0).toUpperCase() + string.slice(1);
  }
  getInputType(value){
    if (typeof(value) == "boolean") return 'checkbox'
    else return 'text';
  }
  getClass(value){
    if (typeof(value) == "boolean") return value ? "true" : "false"
    else return ""
  }
  onClick(e,item){
    e.target.disabled = true;
    setTimeout(()=>{
      e.target.disabled = false;
    },100)
    this.buttonClick.emit(this.getDefaultItem(item));
  }
  getDefaultItem(newItem){
    if (this.remove){
        for(let item of this.data){
            if (this.chekItem(item,newItem))
                return item;
        }
    }
    return newItem
  }
  chekItem(item,newItem){
      for (let key in newItem){
          if (item[key] !== newItem[key]){
              return false;
          }
      }
      return true;
  }
}
 <table class="table table-bordered" *ngIf="viewTable">
  <thead>
      <tr>
          <td *ngFor="let item of (data | currentData:remove)[0] | keys">
              {{jsUcfirst(item.key)}}
          </td>
          <td *ngIf="button"></td>
      </tr>
      <tr>
          <td *ngFor='let item of (data | currentData:remove)[0] | keys'>
              <input  *ngIf="getInputType(item.value) == 'text'"
                      type="text"
                      [(ngModel)]="filter[item.key]">
               <input  *ngIf="getInputType(item.value) == 'checkbox'"
                      type="checkbox"
                      [checked] = "filter[item.key]"
                      (change)="filter[item.key] = !filter[item.key]">     
          </td>
          <td *ngIf="button"></td>
      </tr>
  </thead>
  <tbody>
      <tr *ngFor="let item of (data | currentData:remove) | filterItems:filter" >
          <td *ngFor="let column of item | keys"
              [class]="getClass(column.value)"
              >
          {{column.value}}</td>
          <td *ngIf="button">
              <button (click)="onClick($event,item)"
                      class="btn btn-success">
              {{button}}
              </button>
          </td>
      </tr>
  </tbody>
</table>
