// Angular/src/app/components/table/table.component.ts
import { Component, OnInit, Input, Output, EventEmitter} from '@angular/core';
import { CurrentDataPipe } from '../../pipes';

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css']
})
export class TableComponent implements OnInit {

  @Input() data : string[];
  @Input() button : string; 
  @Input() remove : string[];

  @Output() buttonClick = new EventEmitter<object>();

  filter = {};
  constructor() { }
  get viewTable(){
    return this.data.length > 0;
  }
  ngOnInit() {
    let currentData = new CurrentDataPipe().transform(this.data,this.remove);
    for(let key in currentData[0] ){
        this.filter[key] = (typeof(this.data[0][key]) == "boolean") ? false : '';
    }
  }
  jsUcfirst(string){
    return string.charAt(0).toUpperCase() + string.slice(1);
  }
  getInputType(value){
    if (typeof(value) == "boolean") return 'checkbox'
    else return 'text';
  }
  getClass(value){
    if (typeof(value) == "boolean") return value ? "true" : "false"
    else return ""
  }
  onClick(e,item){
    e.target.disabled = true;
    setTimeout(()=>{
      e.target.disabled = false;
    },100)
    this.buttonClick.emit(this.getDefaultItem(item));
  }
  getDefaultItem(newItem){
    if (this.remove){
        for(let item of this.data){
            if (this.chekItem(item,newItem))
                return item;
        }
    }
    return newItem
  }
  chekItem(item,newItem){
      for (let key in newItem){
          if (item[key] !== newItem[key]){
              return false;
          }
      }
      return true;
  }
}
 <table class="table table-bordered" *ngIf="viewTable">
  <thead>
      <tr>
          <td *ngFor="let item of (data | currentData:remove)[0] | keys">
              {{jsUcfirst(item.key)}}
          </td>
          <td *ngIf="button"></td>
      </tr>
      <tr>
          <td *ngFor='let item of (data | currentData:remove)[0] | keys'>
              <input  *ngIf="getInputType(item.value) == 'text'"
                      type="text"
                      [(ngModel)]="filter[item.key]">
               <input  *ngIf="getInputType(item.value) == 'checkbox'"
                      type="checkbox"
                      [checked] = "filter[item.key]"
                      (change)="filter[item.key] = !filter[item.key]">     
          </td>
          <td *ngIf="button"></td>
      </tr>
  </thead>
  <tbody>
      <tr *ngFor="let item of (data | currentData:remove) | filterItems:filter" >
          <td *ngFor="let column of item | keys"
              [class]="getClass(column.value)"
              >
          {{column.value}}</td>
          <td *ngIf="button">
              <button (click)="onClick($event,item)"
                      class="btn btn-success">
              {{button}}
              </button>
          </td>
      </tr>
  </tbody>
</table>

// Vue/src/components/List/Table.vue
<template>
<div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td v-for="(value,key,index) in currentData[0]" 
                    :key="index">
                    {{jsUcfirst(key)}}
                </td>
                <td v-if="button"></td>
            </tr>
            <tr>
                <td v-for='(value,key,index) in currentData[0]'
                    :key="index">
                    <input :type="getInputType(typeof(value))" 
                           v-model="filter[key]">
                </td>
                <td v-if="button"></td>
            </tr>
        </thead>
        <tbody>
            <tr v-for="(item,index) in filterItems" :key="index">
                <td v-for="(column,key,index) in item"
                    :class="getClass(column)"
                    :key="index"
                    >
                {{column}}</td>
                <td v-if="button">
                    <button @click="onClick($event,item)"
                            class="btn btn-success">
                    {{button}}
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>
</template>

<script>
export default {
    props: {
        data: Array,
        button: String,
        remove: Array
    },
    name: 'myTable',
    data () {
        return{
            filter: {},
        }
    },
    methods:{
        jsUcfirst: (string)=>{
            return string.charAt(0).toUpperCase() + string.slice(1);
        },
        getInputType: (type)=>{
            if (type == "boolean") return 'checkbox'
            else return 'text';
        },
        getClass: (value)=>{
            if (typeof(value) == "boolean") return value ? "true" : "false"
            else return ""
        },
        onClick(e,item){
                e.target.disabled = true;
                setTimeout(()=>{
                    e.target.disabled = false;
                },100)
                this.$emit('buttonClick', this.getDefaultItem(item));
        },
        getDefaultItem(newItem){
            if (this.remove){
                for(let item of this.data){
                    if (this.chekItem(item,newItem))
                        return item;
                }
            }
            return newItem
        },
        chekItem(item,newItem){
            for (let key in newItem){
                if (item[key] !== newItem[key]){
                    return false;
                }
            }
            return true;
        }
    },
    computed: {
        filterItems(){
            return this.currentData.filter((item) => {
                for(let key in this.filter){
                    let check = typeof(this.currentData[0][key]) == "boolean"
                            ? ((this.filter[key] && item[key]) || !this.filter[key])
                            : (item[key].toString().toUpperCase().indexOf(this.filter[key].toString().toUpperCase()) !== -1);
                    if (!check) return false;
                }
                return true;
            });
        },
        currentData(){
            if (this.remove){
                let newdata = [];
                for(let item of this.data){
                    let newItem = {};
                    for(let key in item){
                        if(!this.remove.includes(key.toUpperCase())){
                            newItem[key] = item[key];
                        }
                    }
                    newdata.push(newItem);
                }
                return newdata;
            }
            return this.data;
        },
        viewTable(){
            if (this.data.length == 0){
                return false;
            }else{
                for(let key in this.currentData[0]){
                    let value = (typeof(this.currentData[0][key]) == "boolean") ? false : '';
                    this.$set(this.filter,key,value);
                }
            }
            return true;
        }
    }

}
</script>

<style scoped>
tr:nth-child(2n) td{
    background-color: rgb(218, 218, 218);
}
.true{
    background-color: rgb(80, 245, 39) !important;
}
.false{
    background-color: rgb(248, 33, 33) !important;
    color: white !important;
}

.list-enter-active, .list-leave-active{
    transition: opacity 0.5s;
}

.list-enter{
    opacity: 0;
}

.list-leave-to{
    opacity: 0;
}

</style>
